# Generated by Django 5.0.7 on 2024-07-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("0", "0"),
                            ("1", "Контест"),
                            ("2", "Проект 1"),
                            ("3", "Проект 2"),
                            ("4", "Лабораторная работа по анлизу данных"),
                        ],
                        default="1",
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description_link", models.URLField()),
            ],
        ),
    ]
