# Generated by Django 5.0.7 on 2024-07-09 21:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Task",
        ),
    ]
