# Generated by Django 5.0.7 on 2024-07-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_rename_post_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
