# Generated by Django 5.0.7 on 2024-07-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_task_publish"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dead_line",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
