# Generated by Django 5.0.7 on 2024-07-10 08:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_task_dead_line"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="dead_line",
            new_name="deadline",
        ),
    ]
