# Generated by Django 5.0.7 on 2024-07-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0005_rename_dead_line_task_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("1", "Контест"),
                    ("2", "Проект 1"),
                    ("3", "Проект 2"),
                    ("4", "Лабораторная работа по анлизу данных"),
                ],
                default="0",
                max_length=30,
                unique=True,
            ),
        ),
    ]
