# Generated by Django 5.0.7 on 2024-07-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0006_project1_alter_task_task_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1",
            name="link",
            field=models.TextField(max_length=200),
        ),
    ]
