# Generated by Django 5.0.7 on 2024-07-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0009_alter_project1_link_alter_project1_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1",
            name="user_name",
            field=models.TextField(max_length=30, null=True),
        ),
    ]
