# Generated by Django 5.0.7 on 2024-07-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0010_project1_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1",
            name="score",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="project1",
            name="status",
            field=models.CharField(
                choices=[
                    ("Сhecking", "Сhecking"),
                    ("Rework", "Rework"),
                    ("Accepted", "Accepted"),
                ],
                default="Сhecking",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="project1",
            name="user_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
