# Generated by Django 5.0.7 on 2024-07-15 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0011_project1_score_project1_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project1",
            name="score",
            field=models.FloatField(null=True),
        ),
    ]
