# Generated by Django 5.0.7 on 2024-07-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0012_alter_project1_score"),
    ]

    operations = [
        migrations.AddField(
            model_name="project1",
            name="checker",
            field=models.CharField(default="", max_length=30),
        ),
    ]
