# Generated by Django 5.0.7 on 2024-07-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0014_task_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="Project2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                (
                    "user_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Фамилия и имя"
                    ),
                ),
                ("link", models.URLField(null=True, verbose_name="Ссылка")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Сhecking", "Сhecking"),
                            ("Rework", "Rework"),
                            ("Accepted", "Accepted"),
                        ],
                        default="Сhecking",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "checker",
                    models.CharField(
                        default="", max_length=30, verbose_name="Проверяющий"
                    ),
                ),
                ("score", models.FloatField(null=True, verbose_name="Баллы")),
            ],
            options={
                "verbose_name": "Проект 2",
                "verbose_name_plural": "Проект 2",
            },
        ),
        migrations.AlterModelOptions(
            name="project1",
            options={"verbose_name": "Проект 1", "verbose_name_plural": "Проект 1"},
        ),
        migrations.AlterField(
            model_name="project1",
            name="checker",
            field=models.CharField(
                default="", max_length=30, verbose_name="Проверяющий"
            ),
        ),
        migrations.AlterField(
            model_name="project1",
            name="link",
            field=models.URLField(null=True, verbose_name="Ссылка"),
        ),
        migrations.AlterField(
            model_name="project1",
            name="score",
            field=models.FloatField(null=True, verbose_name="Баллы"),
        ),
        migrations.AlterField(
            model_name="project1",
            name="status",
            field=models.CharField(
                choices=[
                    ("Сhecking", "Сhecking"),
                    ("Rework", "Rework"),
                    ("Accepted", "Accepted"),
                ],
                default="Сhecking",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="project1",
            name="user_name",
            field=models.CharField(
                max_length=30, null=True, verbose_name="Фамилия и имя"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Deadline"),
        ),
        migrations.AlterField(
            model_name="task",
            name="description_link",
            field=models.URLField(verbose_name="Ссылка на описание"),
        ),
        migrations.AlterField(
            model_name="task",
            name="finished",
            field=models.BooleanField(default=False, verbose_name="Завершено"),
        ),
        migrations.AlterField(
            model_name="task",
            name="publish",
            field=models.BooleanField(default=False, verbose_name="Опубликовано"),
        ),
        migrations.AlterField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("0", "0"),
                    ("1", "Контест"),
                    ("2", "Проект 1"),
                    ("3", "Проект 2"),
                    ("4", "Лабораторная работа по анлизу данных"),
                ],
                default="0",
                max_length=30,
                unique=True,
                verbose_name="Тип задания",
            ),
        ),
    ]
