# Generated by Django 5.0.7 on 2024-07-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0015_project2_alter_project1_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField(null=True)),
                (
                    "user_name",
                    models.CharField(
                        max_length=30, null=True, verbose_name="Фамилия и имя"
                    ),
                ),
                ("link", models.URLField(null=True, verbose_name="Ссылка")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Сhecking", "Сhecking"),
                            ("Rework", "Rework"),
                            ("Accepted", "Accepted"),
                        ],
                        default="Сhecking",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "checker",
                    models.CharField(
                        default="", max_length=30, verbose_name="Проверяющий"
                    ),
                ),
                ("score", models.FloatField(null=True, verbose_name="Баллы")),
            ],
            options={
                "verbose_name": "Лабораторная работа",
                "verbose_name_plural": "Лабораторная работа",
            },
        ),
    ]
