# Generated by Django 5.0.7 on 2024-07-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_profile_telegram"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phystech_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
