# Generated by Django 5.0.7 on 2024-07-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_profile_checker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="flow",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Базовый", "Базовый"),
                    ("Продвинутый", "Продвинутый"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seminarists",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Павел Зверев", "Павел Зверев"),
                    ("Александр Маркин", "Александр Маркин"),
                    ("Готовский Геннадий", "Готовский Геннадий"),
                    ("Ромашкина Мария", "Ромашкина Мария"),
                ],
                default="",
                max_length=30,
                unique=True,
            ),
        ),
    ]
