# Generated by Django 5.0.7 on 2024-07-15 12:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_alter_profile_group"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="seminarists",
            new_name="seminarist",
        ),
    ]
