# Generated by Django 5.0.7 on 2024-07-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_rename_seminarists_profile_seminarist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="flow",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Базовый", "Базовый"),
                    ("Продвинутый", "Продвинутый"),
                ],
                default="",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="group",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Б05-301", "Б05-301"),
                    ("Б05-302", "Б05-302"),
                    ("Б05-303", "Б05-303"),
                    ("Б05-304", "Б05-304"),
                    ("Б05-305", "Б05-305"),
                ],
                default="",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="seminarist",
            field=models.CharField(
                choices=[
                    ("", ""),
                    ("Павел Зверев", "Павел Зверев"),
                    ("Александр Маркин", "Александр Маркин"),
                    ("Готовский Геннадий", "Готовский Геннадий"),
                    ("Ромашкина Мария", "Ромашкина Мария"),
                ],
                default="",
                max_length=30,
            ),
        ),
    ]
