# Generated by Django 5.0.7 on 2024-07-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_profile_flow_alter_profile_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="first_name",
            field=models.TextField(blank=True, max_length=18, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="last_name",
            field=models.TextField(blank=True, max_length=18, null=True),
        ),
    ]
