# Generated by Django 5.0.7 on 2024-07-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_alter_profile_first_name_alter_profile_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="fathers_name",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
