# Generated by Django 5.0.7 on 2024-07-15 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0014_alter_profile_checker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="checker",
            field=models.TextField(
                choices=[
                    ("", ""),
                    ("Павел Зверев", "Павел Зверев"),
                    ("Александр Маркин", "Александр Маркин"),
                    ("Готовский Геннадий", "Готовский Геннадий"),
                    ("Ромашкина Мария", "Ромашкина Мария"),
                ],
                default="",
                max_length=40,
            ),
        ),
    ]
